import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useParams,Link,Routes,Route} from 'react-router-dom';
import 'bootstrap/dist/css/bootstrap.min.css';import 'bootstrap-icons/font/bootstrap-icons.css';import './styles.css';

const products=[
{id:1,name:'Rose Lawn Suit',price:2999,stock:12,cat:'Lawn',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSb3SHLzYrNaI_ndtio6Mya6b8xjW7qEMw4o59WLPvfDg&s=10',desc:'Soft printed lawn suit, perfect for everyday Pakistani summer wear.',rating:4.7},
{id:2,name:'Classic White Kurta',price:2499,stock:8,cat:'Kurtas',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST1zTwkISwMydwki2YwzafC8Fn8IYzLhYSatLr3li3YQ&s=10',desc:'A simple and comfortable white kurta for casual wear.',rating:4.8},
{id:3,name:'Black Embroidered Suit',price:4499,stock:5,cat:'Embroidered',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuehZz7IFfJMD0Xh6rN8llpHi9bBSdgxV57t55evdcZw&s=10',desc:'Elegant embroidered outfit for dinners and small events.',rating:4.9},
{id:4,name:'Pastel Pink 2 Piece',price:3799,stock:10,cat:'2 Piece',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgbZFD9H6Df3D679QN1ogME4ba1GfeufZZiNc9l2A2vg&s=10',desc:'Soft pastel two-piece outfit with a modern look.',rating:4.6},
{id:5,name:'Blue Printed Kurti',price:2199,stock:14,cat:'Kurtis',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9jUANWuS9bK5Yk24QIyOV0K8yOur7EjfrjYt1l6_L0Q&s=10',desc:'Comfortable printed kurti for university and daily use.',rating:4.5},
{id:6,name:'Beige Linen Shirt',price:2699,stock:7,cat:'Shirts',img:'https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=800&q=80',desc:'Lightweight beige shirt with a relaxed fit.',rating:4.4},
{id:7,name:'Maroon Festive Dress',price:5499,stock:4,cat:'Festive',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-ySPWjNaw1d_kpVkidY0-xuCDH1lU9m8S9fKFoVse7g&s=10',desc:'Beautiful maroon dress for festive gatherings.',rating:4.9},
{id:8,name:'Mint Green Lawn Set',price:3299,stock:9,cat:'Lawn',img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9mmYGjDiFTint4DSn3Cgkrer9jUYL3zlV9a4rRWTjkw&s',desc:'Fresh mint green lawn set with a comfortable summer feel.',rating:4.6}
];
const cats=['All','Lawn','Kurtas','Embroidered','2 Piece','Kurtis','Shirts','Festive'];
const money=n=>`PKR ${n.toLocaleString()}`;
const getCart=()=>JSON.parse(localStorage.getItem('cart')||'[]');
const saveCart=c=>localStorage.setItem('cart',JSON.stringify(c));
function addCart(p){let c=getCart(),x=c.find(i=>i.id===p.id);x?x.qty++:c.push({...p,qty:1});saveCart(c);window.dispatchEvent(new Event('cart'));}

function Nav(){const [count,setCount]=useState(getCart().reduce((a,b)=>a+b.qty,0));React.useEffect(()=>{let f=()=>setCount(getCart().reduce((a,b)=>a+b.qty,0));addEventListener('cart',f);return()=>removeEventListener('cart',f)},[]);return <nav className="navbar navbar-expand-lg bg-white sticky-top shadow-sm"><div className="container"><Link className="brand" to="/"><i className="bi bi-bag-heart-fill"/> DukaanDost</Link><button className="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span className="navbar-toggler-icon"/></button><div className="collapse navbar-collapse" id="nav"><ul className="navbar-nav mx-auto"><li><Link className="nav-link" to="/">Home</Link></li><li><Link className="nav-link" to="/shop">Shop</Link></li><li><Link className="nav-link" to="/orders">My Orders</Link></li><li><Link className="nav-link" to="/seller">Seller</Link></li></ul><Link className="btn btn-outline-dark me-2" to="/cart"><i className="bi bi-cart3"/> Cart <span className="badge bg-dark">{count}</span></Link><Link className="btn main" to="/login">Login</Link></div></div></nav>}
function Footer(){return <footer><div className="container py-5"><div className="row"><div className="col-md-6"><h4 className="brand">DukaanDost</h4><p>Simple Pakistani clothing shopping with an AI store assistant.</p></div><div className="col-md-3"><h6>Links</h6><Link to="/shop">Shop</Link><br/><Link to="/cart">Cart</Link></div><div className="col-md-3"><h6>Contact</h6><p>Faisalabad, Pakistan<br/>WhatsApp: 0300-1234567<br/>Cash on Delivery</p></div></div><hr/><p className="text-center small mb-0">© 2026 DukaanDost</p></div></footer>}
function Card({p}){return <div className="card product h-100 border-0 shadow-sm"><Link to={'/product/'+p.id}><img src={p.img} className="card-img-top"/></Link><div className="card-body d-flex flex-column"><small>{p.cat}</small><h5>{p.name}</h5><div className="stars">★★★★★ <span>{p.rating}</span></div><h5 className="price">{money(p.price)}</h5><p className="stock">{p.stock} available</p><button className="btn main mt-auto" onClick={()=>{addCart(p);alert('Added to cart')}}>Add to Cart</button></div></div>}
function Home(){return <><section className="hero"><div className="container"><div className="row align-items-center"><div className="col-lg-6"><small>PAKISTANI CLOTHING STORE</small><h1>Simple clothes.<br/>Beautiful style.</h1><p>Shop lawn suits, kurtas, embroidered outfits and everyday clothes at DukaanDost.</p><Link className="btn main btn-lg" to="/shop">Shop Now</Link></div><div className="col-lg-6 mt-4"><img className="hero-img" src={products[2].img}/></div></div></div></section><section className="container py-5"><div className="text-center"><small>OUR COLLECTION</small><h2>Featured Clothes</h2></div><div className="row g-4 mt-2">{products.slice(0,4).map(p=><div className="col-sm-6 col-lg-3" key={p.id}><Card p={p}/></div>)}</div></section><section className="banner"><div className="container text-center"><h2>Need help choosing?</h2><p>Ask our store assistant about price, stock or delivery.</p><button className="btn btn-light" onClick={()=>alert('Use the chat button at the bottom right.')}>Ask Assistant</button></div></section><section className="container py-5"><div className="row g-4"><div className="col-md-4"><div className="info"><i className="bi bi-truck"/><h5>Easy Delivery</h5><p>Cash on Delivery with simple delivery information.</p></div></div><div className="col-md-4"><div className="info"><i className="bi bi-chat-heart"/><h5>AI Assistant</h5><p>Ask questions about real store products.</p></div></div><div className="col-md-4"><div className="info"><i className="bi bi-star"/><h5>Customer Reviews</h5><p>Read ratings and feedback on products.</p></div></div></div></section></>}
function Shop(){const [cat,setCat]=useState('All'),[q,setQ]=useState('');let list=products.filter(p=>(cat==='All'||p.cat===cat)&&p.name.toLowerCase().includes(q.toLowerCase()));return <div className="container py-5"><div className="heading"><small>OUR SHOP</small><h1>Clothing Collection</h1><p>Find something you like and add it to your cart.</p></div><div className="row g-3 mb-4"><div className="col-md-5"><input className="form-control" placeholder="Search clothes..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="col-md-7 cat">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={'btn '+(cat===c?'main':'btn-outline-secondary')}>{c}</button>)}</div></div><div className="row g-4">{list.map(p=><div className="col-sm-6 col-lg-3" key={p.id}><Card p={p}/></div>)}</div></div>}
function Product(){let {id}=useParams(),p=products.find(x=>x.id===Number(id));if(!p)return <div className="container py-5">Product not found</div>;return <div className="container py-5"><div className="row g-5"><div className="col-lg-6"><img src={p.img} className="detail-img"/></div><div className="col-lg-6"><small>{p.cat}</small><h1>{p.name}</h1><div className="stars">★★★★★ {p.rating}</div><h2 className="price">{money(p.price)}</h2><p className="lead">{p.desc}</p><p className="stock">{p.stock} pieces available</p><button className="btn main btn-lg" onClick={()=>{addCart(p);alert('Added to cart')}}>Add to Cart</button><hr/><h5>Customer Reviews</h5><div className="review">★★★★★<br/>“Very comfortable and beautiful.”<br/><small>— Ayesha</small></div><div className="review">★★★★☆<br/>“The color was exactly like the picture.”<br/><small>— Hira</small></div></div></div></div>}
function Cart(){const [cart,setCart]=useState(getCart());const update=(id,d)=>{let c=getCart(),x=c.find(i=>i.id===id);x.qty=Math.max(1,x.qty+d);saveCart(c);setCart(c);window.dispatchEvent(new Event('cart'))};const remove=id=>{let c=getCart().filter(i=>i.id!==id);saveCart(c);setCart(c);window.dispatchEvent(new Event('cart'))};let total=cart.reduce((a,b)=>a+b.price*b.qty,0);if(!cart.length)return <div className="container empty py-5 text-center"><i className="bi bi-cart-x display-1"/><h2>Your cart is empty</h2><Link className="btn main" to="/shop">Shop Now</Link></div>;return <div className="container py-5"><div className="heading"><small>YOUR BAG</small><h1>Shopping Cart</h1></div><div className="row"><div className="col-lg-8">{cart.map(i=><div className="cart-item" key={i.id}><img src={i.img}/><div className="flex-grow-1"><h5>{i.name}</h5><p>{money(i.price)}</p><button onClick={()=>update(i.id,-1)}>-</button><span>{i.qty}</span><button onClick={()=>update(i.id,1)}>+</button></div><button className="btn btn-outline-danger" onClick={()=>remove(i.id)}><i className="bi bi-trash"/></button></div>)}</div><div className="col-lg-4"><div className="summary"><h4>Order Summary</h4><div className="d-flex justify-content-between mt-4"><span>Total</span><b className="price">{money(total)}</b></div><Link className="btn main w-100 mt-4" to="/checkout">Proceed to Checkout</Link></div></div></div></div>}
function Checkout(){const cart=getCart(),total=cart.reduce((a,b)=>a+b.price*b.qty,0),[f,setF]=useState({name:'',phone:'',city:'',address:''}),[err,setErr]=useState(''),nav=useNavigate();function submit(e){e.preventDefault();if(!/^03\d{9}$/.test(f.phone)){setErr('Enter phone like 03001234567');return}localStorage.setItem('order',JSON.stringify({id:Date.now(),...f,items:cart,total,status:'Pending',date:new Date().toLocaleDateString()}));localStorage.removeItem('cart');window.dispatchEvent(new Event('cart'));alert('Order placed with Cash on Delivery!');nav('/orders')}if(!cart.length)return <div className="container py-5">Your cart is empty.</div>;return <div className="container py-5"><div className="heading"><small>CHECKOUT</small><h1>Place Your Order</h1></div><div className="row g-4"><div className="col-lg-7"><form className="form" onSubmit={submit}><h4>Delivery Information</h4>{[['name','Full Name'],['phone','Phone Number'],['city','City']].map(([k,l])=><div key={k} className="mb-3"><label>{l}</label><input className="form-control" value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} required/></div>)}<label>Complete Address</label><textarea className="form-control" rows="4" value={f.address} onChange={e=>setF({...f,address:e.target.value})} required/><div className="cod mt-3"><i className="bi bi-cash-stack"/> Cash on Delivery</div>{err&&<p className="text-danger mt-2">{err}</p>}<button className="btn main w-100 mt-3">Place Order — {money(total)}</button></form></div></div></div>}
function Login(){const nav=useNavigate(),[email,setEmail]=useState(''),[pass,setPass]=useState('');return <div className="auth"><form className="auth-card" onSubmit={e=>{e.preventDefault();localStorage.setItem('user',JSON.stringify({email,role:email.includes('seller')?'seller':'customer'}));nav(email.includes('seller')?'/seller':'/')}}><h2>Welcome Back</h2><p>Login to DukaanDost.</p><input className="form-control mb-3" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="form-control mb-3" type="password" placeholder="Password" value={pass} onChange={e=>setPass(e.target.value)} required/><button className="btn main w-100">Login</button><p className="mt-3">New customer? <Link to="/register">Create account</Link></p><small>Frontend demo: email containing “seller” opens seller area.</small></form></div>}
function Register(){const nav=useNavigate(),[f,setF]=useState({name:'',email:'',phone:'',password:''});return <div className="auth"><form className="auth-card" onSubmit={e=>{e.preventDefault();localStorage.setItem('user',JSON.stringify({...f,role:'customer'}));alert('Account created');nav('/')}}><h2>Create Account</h2><p>Customer registration</p>{[['name','Name'],['email','Email'],['phone','Phone'],['password','Password']].map(([k,l])=><input key={k} className="form-control mb-3" type={k==='password'?'password':k==='email'?'email':'text'} placeholder={l} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} required/>)}<button className="btn main w-100">Create Account</button></form></div>}
function Orders(){let o=JSON.parse(localStorage.getItem('order')||'null');return <div className="container py-5"><div className="heading"><small>CUSTOMER AREA</small><h1>My Orders</h1></div>{!o?<p>No orders yet. <Link to="/shop">Start shopping.</Link></p>:<div className="order"><div className="d-flex justify-content-between"><b>Order DD-{o.id}</b><span className="status">{o.status}</span></div><hr/>{o.items.map(i=><p key={i.id}>{i.name} × {i.qty} — {money(i.price*i.qty)}</p>)}<hr/><b>Total: {money(o.total)}</b></div>}</div>}
function Seller(){const [tab,setTab]=useState('home');return <div className="seller"><div className="container py-5"><div className="heading"><small>SELLER PANEL</small><h1>DukaanDost Store</h1><p>Simple seller area for products, orders, settings and reviews.</p></div>{tab==='home'&&<><div className="row g-3"><Stat n="8" t="Products"/><Stat n="24" t="Orders"/><Stat n="5" t="Pending"/></div><div className="seller-menu mt-4">{[['products','Manage Products'],['orders','Manage Orders'],['settings','Store Settings'],['reviews','Reviews & Sentiment']].map(x=><button key={x[0]} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div></>}{tab==='products'&&<SellerProducts/>}{tab==='orders'&&<SellerOrders/>}{tab==='settings'&&<Settings/>}{tab==='reviews'&&<SellerReviews/>}</div></div>}
function Stat({n,t}){return <div className="col-md-4"><div className="stat"><small>{t}</small><h2>{n}</h2></div></div>}
function SellerProducts(){const [items,setItems]=useState(products),[show,setShow]=useState(false),[f,setF]=useState({name:'',price:'',stock:''});return <div className="mt-4"><button className="btn main mb-3" onClick={()=>setShow(!show)}>+ Add Product</button>{show&&<form className="form mb-4" onSubmit={e=>{e.preventDefault();setItems([...items,{...f,id:Date.now(),price:Number(f.price),stock:Number(f.stock),cat:'Lawn',img:products[0].img}]);setF({name:'',price:'',stock:''});setShow(false)}}><input className="form-control mb-2" placeholder="Product name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input className="form-control mb-2" type="number" placeholder="Price" value={f.price} onChange={e=>setF({...f,price:e.target.value})} required/><input className="form-control mb-2" type="number" placeholder="Stock" value={f.stock} onChange={e=>setF({...f,stock:e.target.value})} required/><button className="btn main">Save Product</button></form>}<div className="table-responsive"><table className="table bg-white"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th></th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.name}</td><td>{money(p.price)}</td><td>{p.stock}</td><td><button className="btn btn-sm btn-outline-danger" onClick={()=>setItems(items.filter(x=>x.id!==p.id))}>Delete</button></td></tr>)}</tbody></table></div></div>}
function SellerOrders(){const [orders,setOrders]=useState([{id:'DD-1001',name:'Ayesha',total:5499,status:'Pending'},{id:'DD-1002',name:'Hira',total:2999,status:'Confirmed'},{id:'DD-1003',name:'Maham',total:4499,status:'Delivered'}]);let change=(id,status)=>setOrders(orders.map(o=>o.id===id?{...o,status}:o));return <div className="mt-4"><div className="table-responsive"><table className="table bg-white"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.name}</td><td>{money(o.total)}</td><td><span className="status">{o.status}</span></td><td>{o.status==='Pending'&&<><button className="btn btn-sm main me-1" onClick={()=>change(o.id,'Confirmed')}>Confirm</button><button className="btn btn-sm btn-outline-danger" onClick={()=>change(o.id,'Cancelled')}>Cancel</button></>}{o.status==='Confirmed'&&<button className="btn btn-sm main" onClick={()=>change(o.id,'Delivered')}>Delivered</button>}</td></tr>)}</tbody></table></div></div>}
function Settings(){const [name,setName]=useState('DukaanDost'),[city,setCity]=useState('Faisalabad, Pakistan'),[wa,setWa]=useState('03001234567'),[delivery,setDelivery]=useState('Delivery takes 3 to 5 working days.');return <form className="form mt-4" onSubmit={e=>{e.preventDefault();alert('Store settings saved')}}><h4>Store Settings</h4><label>Store Name</label><input className="form-control mb-3" value={name} onChange={e=>setName(e.target.value)}/><label>City</label><input className="form-control mb-3" value={city} onChange={e=>setCity(e.target.value)}/><label>WhatsApp</label><input className="form-control mb-3" value={wa} onChange={e=>setWa(e.target.value)}/><label>Delivery Policy</label><textarea className="form-control mb-3" value={delivery} onChange={e=>setDelivery(e.target.value)}/><h5>FAQs</h5><p>Do you offer COD? — Yes.</p><p>How long is delivery? — 3 to 5 working days.</p><p>Can I return? — Contact us within 3 days.</p><button className="btn main">Save Settings</button></form>}
function SellerReviews(){return <div className="mt-4"><div className="row g-3"><Stat n="15" t="Positive"/><Stat n="4" t="Neutral"/><Stat n="2" t="Negative"/></div><div className="row g-3 mt-2">{[['Ayesha','Rose Lawn Suit','Very comfortable and pretty.','Positive'],['Hira','Blue Printed Kurti','Color was nice.','Neutral'],['Maham','Black Embroidered Suit','I did not like the fitting.','Negative']].map(x=><div className="col-md-4" key={x[0]}><div className="review"><b>{x[0]}</b><small className="d-block">{x[1]}</small><span className="status">{x[3]}</span><p className="mt-2">“{x[2]}”</p></div></div>)}</div></div>}
function Chat(){const [open,setOpen]=useState(false),[text,setText]=useState(''),[msgs,setMsgs]=useState([{a:1,t:'Hi! Ask me about clothes, prices, stock or delivery.'}]);function send(e){e.preventDefault();if(!text.trim())return;let q=text.trim(),low=q.toLowerCase(),ans='I can help with DukaanDost clothes, prices, stock and delivery.';let p=products.find(x=>low.includes(x.name.toLowerCase())||low.includes(x.cat.toLowerCase()));if(low.includes('delivery')||low.includes('kitne din'))ans='Delivery usually takes 3 to 5 working days.';else if(low.includes('whatsapp'))ans='You can contact us on WhatsApp: 0300-1234567.';else if(p)ans=`${p.name} is ${money(p.price)} and ${p.stock} pieces are available.`;else if(low.includes('price')||low.includes('kitne')||low.includes('cost'))ans='Tell me the product name or category and I will help.';setMsgs([...msgs,{a:0,t:q},{a:1,t:ans}]);setText('')}return <>{open&&<div className="chat"><div className="chat-head">DukaanDost Assistant <button onClick={()=>setOpen(false)}>×</button></div><div className="messages">{msgs.map((m,i)=><div key={i} className={m.a?'ai':'user'}>{m.t}</div>)}</div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about our clothes..."/><button className="btn main">➤</button></form></div>}<button className="chat-btn" onClick={()=>setOpen(!open)}><i className="bi bi-chat-dots-fill"/></button></>}
function App(){return <BrowserRouter><Nav/><Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Shop/>}/><Route path="/product/:id" element={<Product/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/orders" element={<Orders/>}/><Route path="/seller" element={<Seller/>}/></Routes><Chat/><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
